services:
  blue:
    image: nginx:latest
    container_name: blue
    ports:
      - "${BLUE_PORT}:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
    environment:
      - ACTIVE_COLOR=blue
    entrypoint: ["/nginx-entrypoint.sh"]

  green:
    image: nginx:latest
    container_name: green
    ports:
      - "${GREEN_PORT}:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
    environment:
      - ACTIVE_COLOR=green
    entrypoint: ["/nginx-entrypoint.sh"]

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"  # map host 8080 to container 80
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
    depends_on:
    - blue
    - green
    environment:
      - ACTIVE_COLOR=${ACTIVE_COLOR}
    entrypoint: ["/nginx-entrypoint.sh"]

networks:
  default:
    driver: bridge
