version: "3.8"

services:
  blue:
    image: nginxdemos/hello
    container_name: blue_app
    ports:
      - "${BLUE_PORT}:80"
    environment:
      - COLOR=blue

  green:
    image: nginxdemos/hello
    container_name: green_app
    ports:
      - "${GREEN_PORT}:80"
    environment:
      - COLOR=green

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
    environment:
      - ACTIVE_COLOR=${ACTIVE_POOL}

networks:
  default:
    driver: bridge
