version: "3.8"

services:
  blue:
    image: nginxdemos/hello
    container_name: blue_app
    ports:
      - "${BLUE_PORT}:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
    environment:
      - COLOR=blue
    entrypoint: ["/nginx-entrypoint.sh"]

  green:
    image: nginxdemos/hello
    container_name: green_app
    ports:
      - "${GREEN_PORT}:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
    environment:
      - COLOR=green
    entrypoint: ["/nginx-entrypoint.sh"]

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
    environment:
      - ACTIVE_COLOR=${ACTIVE_COLOR}
    entrypoint: ["/nginx-entrypoint.sh"]

networks:
  default:
    driver: bridge
