blue:
  image: nginx:latest
  container_name: blue
  ports:
    - "${BLUE_PORT}:80"

green:
  image: nginx:latest
  container_name: green
  ports:
    - "${GREEN_PORT}:80"

reverse-proxy:
  image: nginx:latest
  container_name: nginx_reverse_proxy
  ports:
    - "8080:80"
  volumes:
    - ./nginx.template:/etc/nginx/conf.d/default.conf
    - ./nginx-entrypoint.sh:/docker-entrypoint.d/custom-entrypoint.sh:ro
  depends_on:
    - blue
    - green
  environment:
    - ACTIVE_COLOR=${ACTIVE_COLOR}
