services:
  blue:
    image: ${BLUE_IMAGE}
    container_name: blue
    ports:
      - "${BLUE_PORT}:80"

  green:
    image: ${GREEN_IMAGE}
    container_name: green
    ports:
      - "${GREEN_PORT}:80"

  nginx_reverse_proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
      - ./nginx.template:/nginx.template
      - /etc/nginx/conf.d
    environment:
      - ACTIVE_COLOR=${ACTIVE_COLOR}
    entrypoint: ["/bin/sh", "-c", "/nginx-entrypoint.sh"]
